### ISSUE TITLE
order & shipping information screen

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#21]
order & shipping information screen

- is the color and fonts the same as other screens?
- the fill in fields are standard could use the CSS for address, phone fields etc
- Use Region instead of State? 
- Give customer list of regions in their country based on selected country if possible?
- keyboard is over the submit order button

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/ab6ce413-69d2-4530-a4af-ea08ceaedf48)
![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/33de4821-ecff-4b23-87e4-749b3e7ae7a0)

**Comment by KevinKoobs** [comment]
**is the color and fonts the same as other screens?** Yes
**the fill in fields are standard could use the CSS for address, phone fields etc** Fixed in https://github.com/XRPL-Labs/xBuyTangem/commit/82b0b835ed84f5a8cd7629da93f81f69feb76b50
**Use Region instead of State?** Fixed in  https://github.com/XRPL-Labs/xBuyTangem/commit/5c989b124aafc069df04a9f2dc598c1798af276c
**Give customer list of regions in their country based on selected country if possible?** Not for now, nice to have though
**keyboard is over the submit order button** On purpose to give the user full focus on their inputs

**Comment by tomxrpllabs** [comment]
Not sure if this is a bug/issue but zipcode field shows alphabet keyboard when testing with my ihpone. (shouldnt this be showing numerics)

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/ad17a9b2-d280-4de2-b99b-18c657a87430)
